#!/bin/bash
#
# Build the bundled ingredient icon catalogue from the watercolour masters.
#
#   Tools/ingredient-icons/build.sh [path-to-masters]
#
# The masters are 469 transparent PNGs at 1024×1024 with a manifest.json, and
# they weigh 505 MB. They stay outside the repository: git cannot forget a
# blob once it has one, so only the downscaled copies are committed.
#
# Writes three generated artefacts, all from one read of the manifest so they
# cannot drift apart:
#
#   Ladle/Resources/IngredientIcons.xcassets/<slug>.imageset/  the art
#   Ladle/Resources/IngredientIcons.xcassets/manifest.json     what shipped
#   Ladle/Design/IngredientIconCatalogue.swift                 the slug universe
#
# Re-run it after changing the masters, then `xcodegen generate` if the set of
# files changed, and commit the result.

set -euo pipefail

MASTERS="${1:-$HOME/Downloads/cooking-app-icons-complete}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CATALOG="$ROOT/Ladle/Resources/IngredientIcons.xcassets"
SWIFT_TABLE="$ROOT/Ladle/Design/IngredientIconCatalogue.swift"

# 192px is 2× the icon set README's 96-point tile target and 4.8× the
# 40-point row this app draws them in, so a 3× phone still has more pixels
# than it needs. 96px would be soft at 3×; 288px more than doubles the
# weight for detail no row can show.
readonly LONGEST_EDGE=192

if [[ ! -f "$MASTERS/manifest.json" ]]; then
    echo "error: no manifest.json under $MASTERS" >&2
    echo "       pass the masters directory as the first argument" >&2
    exit 1
fi
command -v sips >/dev/null || { echo "error: sips is required" >&2; exit 1; }
command -v python3 >/dev/null || { echo "error: python3 is required" >&2; exit 1; }

echo "masters:  $MASTERS"
echo "catalog:  $CATALOG"

# Rebuild from empty so a slug removed from the manifest leaves the bundle.
rm -rf "$CATALOG"
mkdir -p "$CATALOG"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# One pass over the manifest writes every Contents.json, the shipped
# manifest, the Swift table, and the list of downscales still to run.
python3 - "$MASTERS" "$CATALOG" "$SWIFT_TABLE" "$WORK/jobs" <<'PYTHON'
import json
import os
import sys

masters, catalog, swift_table, jobs_path = sys.argv[1:5]
assets = json.load(open(os.path.join(masters, "manifest.json")))["assets"]
assets.sort(key=lambda a: a["slug"])

CONTENTS = {"info": {"author": "xcode", "version": 1}}


def write_json(path, payload):
    with open(path, "w") as handle:
        json.dump(payload, handle, indent=2)
        handle.write("\n")


write_json(os.path.join(catalog, "Contents.json"), CONTENTS)

jobs = []
for asset in assets:
    slug = asset["slug"]
    imageset = os.path.join(catalog, f"{slug}.imageset")
    os.makedirs(imageset, exist_ok=True)
    # The downscaled PNG is the 2x slot; 1x and 3x are declared and left
    # empty, the shape docs/verification/2026-07-29-asset-catalog-scale-slots
    # settled for every image set in this project.
    write_json(
        os.path.join(imageset, "Contents.json"),
        {
            "images": [
                {"idiom": "universal", "scale": "1x"},
                {"filename": f"{slug}.png", "idiom": "universal", "scale": "2x"},
                {"idiom": "universal", "scale": "3x"},
            ],
            **CONTENTS,
        },
    )
    jobs.append(
        f"{os.path.join(masters, asset['file'])}\t{os.path.join(imageset, slug + '.png')}"
    )

with open(jobs_path, "w") as handle:
    handle.write("\n".join(jobs) + "\n")

# What shipped, for the resolver's existence test to check itself against.
write_json(
    os.path.join(catalog, "manifest.json"),
    {
        "generatedBy": "Tools/ingredient-icons/build.sh",
        "source": "cooking-app-icons-complete 1.0.0",
        "longestEdge": 192,
        "count": len(assets),
        "assets": [
            {
                "slug": a["slug"],
                "displayName": a["display_name"],
                "category": a["category"],
                "container": a["container"],
            }
            for a in assets
        ],
    },
)


def wrap(slugs):
    lines, line = [], "    "
    for slug in slugs:
        if len(line) + len(slug) > 76:
            lines.append(line.rstrip())
            line = "    "
        line += slug + " "
    lines.append(line.rstrip())
    return "\n".join(lines)


illustrated = [a["slug"] for a in assets if not a["container"]]
containers = [a["slug"] for a in assets if a["container"]]

with open(swift_table, "w") as handle:
    handle.write(
        f'''// Generated by Tools/ingredient-icons/build.sh — do not edit by hand.
//
// The slug universe `IngredientIconResolver` matches against. It is static
// data rather than a read of the bundled manifest so the resolver stays a
// pure function: no bundle, no file system, callable from a test with no
// host app around it.
//
// Two lists rather than one array of records because a {len(assets)}-element array
// literal is slow for the type checker and unreadable in a diff, and the
// only fact the resolver needs beyond the slug is which kind of art it is.

import Foundation

enum IngredientIconCatalogue {{
    /// Painted ingredients: the watercolour of the thing itself.
    static let illustrated: Set<String> = slugs(in: illustratedList)

    /// Tinted pantry containers — a jar, bottle, bag, box, can or tub in the
    /// category's colour. The art for everything a cook keeps in a cupboard.
    static let containers: Set<String> = slugs(in: containerList)

    /// Every slug in the bundled catalogue.
    static let all: Set<String> = illustrated.union(containers)

    /// The slugs eligible for a given resolver call.
    static func eligible(includesContainers: Bool) -> Set<String> {{
        includesContainers ? all : illustrated
    }}

    private static func slugs(in list: String) -> Set<String> {{
        Set(list.split(whereSeparator: \\.isWhitespace).map(String.init))
    }}

    /// {len(illustrated)} painted ingredients.
    private static let illustratedList = """
{wrap(illustrated)}
    """

    /// {len(containers)} pantry containers.
    private static let containerList = """
{wrap(containers)}
    """
}}
'''
    )

print(f"manifest: {len(assets)} assets ({len(illustrated)} painted, {len(containers)} containers)")
PYTHON

echo "downscaling to ${LONGEST_EDGE}px..."
# sips is one process per file, so run them wide; 469 of them serially is a
# minute of waiting for no reason.
tr '\t' '\n' < "$WORK/jobs" \
    | xargs -P 8 -n 2 sh -c "sips -Z $LONGEST_EDGE \"\$0\" --out \"\$1\" >/dev/null"

WRITTEN="$(find "$CATALOG" -name '*.png' | wc -l | tr -d ' ')"
echo "wrote $WRITTEN images, $(du -sh "$CATALOG" | cut -f1) total"
echo "wrote ${SWIFT_TABLE#"$ROOT"/}"
