// Generated by Tools/ingredient-icons/build.sh — do not edit by hand.
//
// The slug universe `IngredientIconResolver` matches against. It is static
// data rather than a read of the bundled manifest so the resolver stays a
// pure function: no bundle, no file system, callable from a test with no
// host app around it.
//
// Two lists rather than one array of records because a 469-element array
// literal is slow for the type checker and unreadable in a diff, and the
// only fact the resolver needs beyond the slug is which kind of art it is.

import Foundation

enum IngredientIconCatalogue {
    /// Painted ingredients: the watercolour of the thing itself.
    static let illustrated: Set<String> = slugs(in: illustratedList)

    /// Tinted pantry containers — a jar, bottle, bag, box, can or tub in the
    /// category's colour. The art for everything a cook keeps in a cupboard.
    static let containers: Set<String> = slugs(in: containerList)

    /// Every slug in the bundled catalogue.
    static let all: Set<String> = illustrated.union(containers)

    /// The slugs eligible for a given resolver call.
    static func eligible(includesContainers: Bool) -> Set<String> {
        includesContainers ? all : illustrated
    }

    private static func slugs(in list: String) -> Set<String> {
        Set(list.split(whereSeparator: \.isWhitespace).map(String.init))
    }

    /// 223 painted ingredients.
    private static let illustratedList = """
    almond anchovy apple-granny-smith apple-honeycrisp apricot artichoke
    arugula asparagus avocado bacon baguette banana basil-fresh beef-brisket
    beef-chuck beef-ground beef-ribeye beef-short-ribs beef-sirloin beet
    bell-pepper-green bell-pepper-red bell-pepper-yellow blackberry
    blueberry bok-choy brazil-nut bread-sourdough bread-white
    bread-whole-wheat brioche broccoli broccolini brussels-sprouts
    butter-salted butter-unsalted butternut-squash cabbage-green cabbage-red
    cantaloupe carrot cashew cauliflower celery chard cheese-blue
    cheese-brie cheese-cheddar cheese-cotija cheese-cream cheese-feta
    cheese-goat cheese-gruyere cheese-halloumi cheese-mascarpone
    cheese-mozzarella cheese-parmesan cheese-ricotta cherry chestnut
    chicken-breast chicken-drumstick chicken-thigh chicken-whole
    chicken-wings chives chocolate-bittersweet chocolate-chips
    chocolate-unsweetened chorizo ciabatta cilantro cinnamon-stick clams
    clementine coconut cod collard-greens corn crab cranberry creme-fraiche
    cucumber curry-leaves daikon date dill-fresh duck-breast edamame
    egg-chicken egg-duck egg-white egg-yolk eggplant endive fennel fig
    galangal garlic ginger grape-green grape-red grapefruit green-beans
    guava halibut ham hazelnut horseradish jalapeno kale kiwi kohlrabi
    lamb-chop lamb-ground leek lemon lemongrass lettuce-iceberg
    lettuce-romaine lime lobster lychee macadamia mackerel mango mint-fresh
    mushroom-button mushroom-cremini mushroom-portobello mushroom-shiitake
    mussels naan nectarine noodles-egg noodles-ramen noodles-rice
    noodles-soba noodles-udon octopus okra onion-red onion-white
    onion-yellow orange oregano-fresh oysters pancetta papaya parsley-flat
    parsnip passion-fruit pasta-farfalle pasta-fettuccine pasta-fusilli
    pasta-lasagna pasta-macaroni pasta-orzo pasta-penne pasta-rigatoni
    pasta-spaghetti peach peanut pear peas pecan persimmon pine-nuts
    pineapple pistachio pita plantain plum pomegranate pork-belly pork-chop
    pork-ground pork-shoulder potato-russet potato-yukon prosciutto pumpkin
    pumpkin-seeds radish raisin raspberry rosemary-fresh sage-fresh
    salmon-fillet sardines sausage-italian scallion scallops sea-bass seitan
    serrano-pepper shallot shiso shrimp snap-peas snapper spinach squid
    star-anise strawberry sunflower-seeds sweet-potato tarragon-fresh tempeh
    thyme-fresh tilapia tofu-extra-firm tofu-firm tofu-silken tortilla-corn
    tortilla-flour trout tuna-steak turmeric-root vanilla-bean walnut
    watermelon zucchini
    """

    /// 246 pantry containers.
    private static let containerList = """
    agave-nectar ajwain allspice amchur anise-seed annatto
    artichoke-hearts-jarred asafoetida avocado-oil baking-powder baking-soda
    barley basil-dried bay-leaf bbq-sauce beer black-beans black-eyed-peas
    black-pepper-ground black-pepper-whole bonito-flakes bouillon-cubes
    brandy breadcrumbs buckwheat bulgur buttermilk cannellini-beans
    canola-oil capers caraway cardamom-black cardamom-green cayenne
    celery-seed chia-seeds chickpeas chili-flakes chili-oil chili-powder
    chipotle-powder chipotles-adobo cinnamon-ground clove cocoa-powder
    coconut-cream coconut-milk-canned coconut-oil condensed-milk
    coriander-ground coriander-seed corn-canned corn-syrup cornmeal
    cornstarch couscous cream-of-tartar cumin-ground cumin-seed curry-powder
    dashi date-syrup demi-glace dill-dried doubanjiang duck-fat
    espresso-powder evaporated-milk farro fava-beans fennel-seed fenugreek
    fish-sauce five-spice flaxseed flour-all-purpose flour-almond
    flour-bread flour-cake flour-coconut flour-rye flour-whole-wheat freekeh
    garam-masala garlic-powder gelatin ghee ginger-ground gochugaru
    gochujang grapeseed-oil green-chiles harissa hearts-of-palm heavy-cream
    hemp-seeds herbes-de-provence hoisin-sauce honey honey-mustard
    horseradish-prepared hot-sauce italian-seasoning jaggery juniper-berries
    ketchup kewpie-mayo kidney-beans kimchi kombu lard lentils-brown
    lentils-green lentils-red lima-beans mace maple-syrup marjoram-dried
    matcha-powder mayonnaise milk-coconut milk-oat milk-whole millet
    mint-dried mirin miso-red miso-white molasses mung-beans mustard-dijon
    mustard-seed mustard-whole-grain mustard-yellow navy-beans nigella-seeds
    nutmeg nutritional-yeast oats-rolled oats-steel-cut olive-oil-evoo
    olive-oil-light olives-green olives-kalamata onion-powder oregano-dried
    oyster-sauce panko paprika-smoked paprika-sweet parsley-dried peanut-oil
    peppercorn-pink peppercorn-sichuan pesto pickles pinto-beans polenta
    ponzu poppy-seeds pumpkin-puree quinoa ras-el-hanout relish rice-arborio
    rice-basmati rice-brown rice-jasmine rice-short-grain rice-wild
    rice-wine roasted-red-peppers rosemary-dried saffron sage-dried sake
    salsa salt-flaky salt-kosher salt-table sambal-oelek sauerkraut schmaltz
    semolina sesame-oil-toasted sesame-seeds-black sesame-seeds-white sherry
    shortening sour-cream soy-curls soy-sauce split-peas sriracha stock-beef
    stock-chicken stock-fish stock-vegetable sugar-brown-dark
    sugar-brown-light sugar-coconut sugar-granulated sugar-powdered
    sugar-turbinado sumac sun-dried-tomatoes sunflower-oil sweet-chili-sauce
    tahini tamari tapioca-starch tarragon-dried thyme-dried tomato-paste
    tomatoes-crushed tomatoes-diced tomatoes-san-marzano toor-dal
    tuna-canned turmeric-ground tvp urad-dal vanilla-extract
    vinegar-apple-cider vinegar-balsamic vinegar-black vinegar-champagne
    vinegar-malt vinegar-red-wine vinegar-rice vinegar-sherry vinegar-white
    vinegar-white-wine vital-wheat-gluten walnut-oil water-chestnuts
    wheat-berries white-pepper wine-red wine-white worcestershire
    xanthan-gum xo-sauce yeast-active-dry yogurt-greek zaatar
    """
}
