"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-07-23 23:03:27.557638
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_videos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("platform_video_id", sa.String(length=255), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column(
            "public_access_confirmed_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "source_revision", sa.String(length=255), server_default="1", nullable=False
        ),
        sa.Column(
            "metadata_json",
            sa.JSON(),
            server_default=sa.text("'{}'::json"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "platform IN ('youtube', 'tiktok', 'instagram')",
            name="ck_source_videos_platform",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_videos")),
        sa.UniqueConstraint(
            "platform", "platform_video_id", name="uq_source_videos_platform_identity"
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("merged_into_user_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint("kind IN ('guest', 'apple')", name="ck_users_kind"),
        sa.ForeignKeyConstraint(
            ["merged_into_user_id"],
            ["users.id"],
            name=op.f("fk_users_merged_into_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "apple_identities",
        sa.Column("apple_sub", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_apple_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("apple_sub", name=op.f("pk_apple_identities")),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("installation_id", sa.String(length=255), nullable=False),
        sa.Column(
            "attestation_state",
            sa.String(length=32),
            server_default="unverified",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_devices_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("installation_id", name=op.f("uq_devices_installation_id")),
    )
    op.create_table(
        "extraction_cache",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_video_id", sa.Uuid(), nullable=False),
        sa.Column("source_revision", sa.String(length=255), nullable=False),
        sa.Column("contract_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("template_json", sa.JSON(), nullable=False),
        sa.Column("review_status", sa.String(length=24), nullable=False),
        sa.Column("thumbnail_object_key", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "review_status IN ('ready', 'needsReview')",
            name="ck_extraction_cache_review_status",
        ),
        sa.ForeignKeyConstraint(
            ["source_video_id"],
            ["source_videos.id"],
            name=op.f("fk_extraction_cache_source_video_id_source_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_cache")),
        sa.UniqueConstraint(
            "source_video_id",
            "source_revision",
            "contract_version",
            "prompt_version",
            "model_id",
            name="uq_extraction_cache_identity",
        ),
    )
    op.create_table(
        "user_sync_state",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("next_sequence", sa.BigInteger(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "next_sequence > 0", name="ck_user_sync_state_next_sequence_positive"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sync_state_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_sync_state")),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("token_family_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column(
            "previous_refresh_token_hash", sa.LargeBinary(length=32), nullable=True
        ),
        sa.Column("previous_valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_auth_sessions_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint(
            "refresh_token_hash", name=op.f("uq_auth_sessions_refresh_token_hash")
        ),
    )
    op.create_index(
        op.f("ix_auth_sessions_token_family_id"),
        "auth_sessions",
        ["token_family_id"],
        unique=False,
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_video_id", sa.Uuid(), nullable=True),
        sa.Column("source_cache_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("creator_name", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=False),
        sa.Column("preparation_minutes", sa.Integer(), nullable=True),
        sa.Column("cooking_minutes", sa.Integer(), nullable=True),
        sa.Column("total_minutes", sa.Integer(), nullable=True),
        sa.Column("servings", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "favorite", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("review_status", sa.String(length=24), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "review_status IN ('ready', 'needsReview')", name="ck_recipes_review_status"
        ),
        sa.CheckConstraint(
            "source IN ('tiktok', 'instagram', 'youtube', 'other')",
            name="ck_recipes_source",
        ),
        sa.CheckConstraint("revision > 0", name="ck_recipes_revision_positive"),
        sa.ForeignKeyConstraint(
            ["source_cache_id"],
            ["extraction_cache.id"],
            name=op.f("fk_recipes_source_cache_id_extraction_cache"),
        ),
        sa.ForeignKeyConstraint(
            ["source_video_id"],
            ["source_videos.id"],
            name=op.f("fk_recipes_source_video_id_source_videos"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_recipes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipes")),
    )
    op.create_index(op.f("ix_recipes_user_id"), "recipes", ["user_id"], unique=False)
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_video_id", sa.Uuid(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "status", sa.String(length=24), server_default="parsing", nullable=False
        ),
        sa.Column(
            "stage", sa.String(length=32), server_default="admitted", nullable=False
        ),
        sa.Column("failure_reason", sa.String(length=32), nullable=True),
        sa.Column("diagnostic_code", sa.String(length=128), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "bypass_cache",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("correction_notes_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("pasted_text_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("current_recipe_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_recipe_id", sa.Uuid(), nullable=True),
        sa.Column("cache_entry_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("base_recipe_revision", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "source IN ('tiktok', 'instagram', 'youtube', 'other')",
            name="ck_import_jobs_source",
        ),
        sa.CheckConstraint(
            "status IN ('parsing', 'ready', 'needsReview', 'failed')",
            name="ck_import_jobs_status",
        ),
        sa.ForeignKeyConstraint(
            ["cache_entry_id"],
            ["extraction_cache.id"],
            name=op.f("fk_import_jobs_cache_entry_id_extraction_cache"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_recipe_id"],
            ["recipes.id"],
            name=op.f("fk_import_jobs_candidate_recipe_id_recipes"),
        ),
        sa.ForeignKeyConstraint(
            ["current_recipe_id"],
            ["recipes.id"],
            name=op.f("fk_import_jobs_current_recipe_id_recipes"),
        ),
        sa.ForeignKeyConstraint(
            ["source_video_id"],
            ["source_videos.id"],
            name=op.f("fk_import_jobs_source_video_id_source_videos"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_import_jobs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_jobs")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_import_jobs_user_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_import_jobs_user_id"), "import_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_text", sa.Text(), nullable=True),
        sa.Column(
            "normalized_quantity", sa.Numeric(precision=18, scale=6), nullable=True
        ),
        sa.Column("unit", sa.String(length=64), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("preparation", sa.Text(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_ingredients_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredients")),
        sa.UniqueConstraint("recipe_id", "id", name="uq_ingredients_recipe_id"),
        sa.UniqueConstraint(
            "recipe_id", "order_index", name="uq_ingredients_recipe_order"
        ),
    )
    op.create_table(
        "nutrition",
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("calories", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("protein_grams", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "carbohydrate_grams", sa.Numeric(precision=18, scale=6), nullable=True
        ),
        sa.Column("fat_grams", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "saturated_fat_grams", sa.Numeric(precision=18, scale=6), nullable=True
        ),
        sa.Column("fiber_grams", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("sugar_grams", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "sodium_milligrams", sa.Numeric(precision=18, scale=6), nullable=True
        ),
        sa.Column("serving_basis", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("is_estimated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_nutrition_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("recipe_id", name=op.f("pk_nutrition")),
    )
    op.create_table(
        "recipe_changes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("recipe_revision", sa.Integer(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('upsert', 'delete')", name="ck_recipe_changes_kind"
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_changes_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_recipe_changes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "sequence", name=op.f("pk_recipe_changes")),
    )
    op.create_table(
        "recipe_images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_images_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_images")),
        sa.UniqueConstraint(
            "recipe_id", "order_index", name="uq_recipe_images_recipe_order"
        ),
    )
    op.create_table(
        "recipe_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_steps_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_steps")),
        sa.UniqueConstraint("recipe_id", "id", name="uq_recipe_steps_recipe_id"),
        sa.UniqueConstraint(
            "recipe_id", "order_index", name="uq_recipe_steps_recipe_order"
        ),
    )
    op.create_table(
        "detected_timers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_step_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_step_id"],
            ["recipe_steps.id"],
            name=op.f("fk_detected_timers_recipe_step_id_recipe_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detected_timers")),
    )
    op.create_table(
        "extraction_claims",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_video_id", sa.Uuid(), nullable=False),
        sa.Column("owner_job_id", sa.Uuid(), nullable=False),
        sa.Column("claim_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_job_id"],
            ["import_jobs.id"],
            name=op.f("fk_extraction_claims_owner_job_id_import_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_video_id"],
            ["source_videos.id"],
            name=op.f("fk_extraction_claims_source_video_id_source_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_claims")),
    )
    op.create_index(
        "uq_extraction_claims_active_source_video",
        "extraction_claims",
        ["source_video_id"],
        unique=True,
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.create_table(
        "field_uncertainties",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient_id", sa.Uuid(), nullable=True),
        sa.Column("step_id", sa.Uuid(), nullable=True),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_field_uncertainties_ingredient_id_ingredients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_field_uncertainties_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["recipe_steps.id"],
            name=op.f("fk_field_uncertainties_step_id_recipe_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_uncertainties")),
    )
    op.create_table(
        "other_nutrients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nutrition_recipe_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["nutrition_recipe_id"],
            ["nutrition.recipe_id"],
            name=op.f("fk_other_nutrients_nutrition_recipe_id_nutrition"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_other_nutrients")),
    )
    op.create_table(
        "provider_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_job_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("external_job_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("billed_units", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["import_jobs.id"],
            name=op.f("fk_provider_attempts_import_job_id_import_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_attempts")),
        sa.UniqueConstraint(
            "import_job_id",
            "idempotency_key",
            name="uq_provider_attempts_job_idempotency",
        ),
    )
    op.create_table(
        "recipe_slot_reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("import_job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state", sa.String(length=16), server_default="reserved", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('reserved', 'consumed', 'released')",
            name="ck_recipe_slot_reservations_state",
        ),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["import_jobs.id"],
            name=op.f("fk_recipe_slot_reservations_import_job_id_import_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_recipe_slot_reservations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_slot_reservations")),
        sa.UniqueConstraint(
            "import_job_id", name=op.f("uq_recipe_slot_reservations_import_job_id")
        ),
    )
    op.create_index(
        op.f("ix_recipe_slot_reservations_user_id"),
        "recipe_slot_reservations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "step_ingredients",
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id", "ingredient_id"],
            ["ingredients.recipe_id", "ingredients.id"],
            name="fk_step_ingredients_ingredient_same_recipe",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id", "step_id"],
            ["recipe_steps.recipe_id", "recipe_steps.id"],
            name="fk_step_ingredients_step_same_recipe",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "recipe_id", "step_id", "ingredient_id", name=op.f("pk_step_ingredients")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("step_ingredients")
    op.drop_index(
        op.f("ix_recipe_slot_reservations_user_id"),
        table_name="recipe_slot_reservations",
    )
    op.drop_table("recipe_slot_reservations")
    op.drop_table("provider_attempts")
    op.drop_table("other_nutrients")
    op.drop_table("field_uncertainties")
    op.drop_index(
        "uq_extraction_claims_active_source_video",
        table_name="extraction_claims",
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.drop_table("extraction_claims")
    op.drop_table("detected_timers")
    op.drop_table("recipe_steps")
    op.drop_table("recipe_images")
    op.drop_table("recipe_changes")
    op.drop_table("nutrition")
    op.drop_table("ingredients")
    op.drop_index(op.f("ix_import_jobs_user_id"), table_name="import_jobs")
    op.drop_table("import_jobs")
    op.drop_index(op.f("ix_recipes_user_id"), table_name="recipes")
    op.drop_table("recipes")
    op.drop_index(op.f("ix_auth_sessions_token_family_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_table("user_sync_state")
    op.drop_table("extraction_cache")
    op.drop_table("devices")
    op.drop_table("apple_identities")
    op.drop_table("users")
    op.drop_table("source_videos")
    # ### end Alembic commands ###
